COMPILER = clang++
FLAGS = --std=c++98 -Wall -Wextra -Werror


vector:
	@$(COMPILER) $(FLAGS)	main.cpp -o vector.out 

map:
	@$(COMPILER) $(FLAGS)	main2.cpp -o map.out 

stack:
	@$(COMPILER) $(FLAGS)	main3.cpp -o stack.out 

clean:
	rm -f vector.out map.out stack.out
